name: Ops.
description: A social media for cooking recipes.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  image_picker: ^0.8.7+5
  image_picker_for_web: ^2.1.12
  supabase_flutter: ^1.9.2
  shared_preferences: ^2.1.1
  flutter_card_swiper: ^5.1.0
  flutter_svg: ^2.0.7
  flutter_boring_avatars: ^1.0.1
  google_mobile_ads: ^3.1.0
  flutter_staggered_grid_view: ^0.7.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0





flutter:
  uses-material-design: true

  assets:
    - assets/328.svg
    - assets/splash.gif


  fonts:
    - family: Varela
      fonts:
        - asset: assets/fonts/varela.ttf
